// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// JDModel is the predicate function for jdmodel builders.
type JDModel func(*sql.Selector)

// QQModel is the predicate function for qqmodel builders.
type QQModel func(*sql.Selector)

// SFModel is the predicate function for sfmodel builders.
type SFModel func(*sql.Selector)
