// Code generated by entc, DO NOT EDIT.

package jdmodel

const (
	// Label holds the string label denoting the jdmodel type in the database.
	Label = "jd_model"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldNickname holds the string denoting the nickname field in the database.
	FieldNickname = "nickname"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldIDNumber holds the string denoting the id_number field in the database.
	FieldIDNumber = "id_number"
	// FieldPhoneNumber holds the string denoting the phone_number field in the database.
	FieldPhoneNumber = "phone_number"

	// Table holds the table name of the jdmodel in the database.
	Table = "jd"
)

// Columns holds all SQL columns for jdmodel fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldNickname,
	FieldPassword,
	FieldEmail,
	FieldIDNumber,
	FieldPhoneNumber,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
