// Code generated by entc, DO NOT EDIT.

package sfmodel

const (
	// Label holds the string label denoting the sfmodel type in the database.
	Label = "sf_model"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldPhoneNumber holds the string denoting the phone_number field in the database.
	FieldPhoneNumber = "phone_number"
	// FieldAddress holds the string denoting the address field in the database.
	FieldAddress = "address"

	// Table holds the table name of the sfmodel in the database.
	Table = "sf"
)

// Columns holds all SQL columns for sfmodel fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldPhoneNumber,
	FieldAddress,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
