// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/kallydev/privacy/ent/runtime.go

const (
	Version = "v0.5.0"                                          // Version of ent codegen.
	Sum     = "h1:NlDQDxJi1X6+20CCjRQgu8UqvRhQNm5ocPBCQYdxC/8=" // Sum of ent codegen.
)
