// Code generated by entc, DO NOT EDIT.

package qqmodel

const (
	// Label holds the string label denoting the qqmodel type in the database.
	Label = "qq_model"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldQqNumber holds the string denoting the qq_number field in the database.
	FieldQqNumber = "qq_number"
	// FieldPhoneNumber holds the string denoting the phone_number field in the database.
	FieldPhoneNumber = "phone_number"

	// Table holds the table name of the qqmodel in the database.
	Table = "qq"
)

// Columns holds all SQL columns for qqmodel fields.
var Columns = []string{
	FieldID,
	FieldQqNumber,
	FieldPhoneNumber,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
